#!/usr/bin/python
"""
For each .txt file in the command line, check if the output of the
XML-RPC service is identical to the .key file (which was previously
generated by the standalove code)
"""

import xmlrpclib

s = xmlrpclib.ServerProxy('http://127.0.0.1:8000')


import sys
assert len(sys.argv) > 0
for ftxt in sys.argv[1:]:
    assert ftxt[-4:] == ".txt"
    fkey = ftxt[:-4] + ".key"
#    print ftxt, fkey
    txt = open(ftxt).read()
    keywords = s.kea.extractKeyphrases(txt)
    print keywords
    origkeywords = [l[:-1] for l in open(fkey).xreadlines()]
    print origkeywords
